version: 2

sources:
  - name: kestradb              # What you use in source('kestradb', ...)
    database: AwsDataCatalog    # This is the actual Athena catalog
    schema: kestradb            # This is the actual Athena database
    tables:
      - name: global_indicators_ext

models:
  - name: stg_kestradb__global_indicators_ext
    description: "Staging model for global indicators external table."
    columns:
      - name: country_code
        description: "ISO country code"
      - name: country_name
        description: "Full country name"
      - name: year
        description: "Year of the indicator"
      - name: value
        description: "Recorded value for the indicator"
  - name: dim_country
    description: Dimension table for all valid countries
    columns:
      - name: country_code
        description: ISO code or regional code
        tests:
          - not_null
          - unique
      - name: country_name
        description: Full name of the country
        tests:
          - not_null

  - name: fct_global_indicators
    description: Fact table for cleaned and filtered global indicators data
    columns:
      - name: country_code
        description: Country or region code
        tests:
          - not_null
      - name: indicator_name
        description: Human-readable name of the indicator
        tests:
          - not_null
      - name: year
        description: Year of observation
        tests:
          - not_null
      - name: value
        description: Measured value of the indicator
        tests:
          - not_null
